config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :auctions do
    resources :bids, only: [:new, :create, :destroy]
  end

  root 'auctions#index'
end

app/models/auction.rb
class Auction < ActiveRecord::Base


  belongs_to :user

  has_many :bids, dependent: :destroy


  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 5 }



include AASM

aasm whiny_transitions: false do
  state :draft, initial: true
  state :published

  event :publish do
    transitions from: :draft, to: :published
    end
  end


  def self.published
    where(aasm_state: :published)
  end


end

app/models/bid.rb
class Bid < ActiveRecord::Base
  # validate :cannot_bid_on_self

  # def cannot_bid_on_self
  #   current_user == auction.user_id
  #   flash[:alert] = "Cant bid on self auction"
  # end

  belongs_to :auction

  validates :amount, presence: true,
                     numericality: { greater_than_or_equal_to: 1 }


end

app/models/bidding.rb
class Bidding < ActiveRecord::Base
  belongs_to :bid
  belongs_to :auction
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :auctions, dependent: :nullify

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def authenticate_user!
  redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
end

def user_signed_in?
  current_user.present?
end
helper_method :user_signed_in?

def current_user
  @current_user ||= User.find_by_id session[:user_id]
end
helper_method :current_user

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
before_action :authenticate_user!, except: [:show, :index]


  def new
    @auction = Auction.new
  end


  def index
    @auction = Auction.all
  end

  def create
    @auction      = Auction.new(auction_params)
    @auction.user = current_user
      if @auction.save
       redirect_to root_path, notice: "Sweet"
      else
        render :new
        flash[:alert] = "Did not create"
      end
  end

  def show
    @auction = Auction.find(params[:id])
    @bid     = Bid.new
  end

  private

  def auction_params
    params.require(:auction).permit(:title, :description, :end_date, :price, :user_id)
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def create
    @bid         = Bid.new(bid_params)
    @auction     = Auction.find params[:auction_id]
    @bid.auction = @auction
    respond_to do |format|
      if @bid.save
        format.html { redirect_to auction_path(@auction), notice: "good job" }
        format.js { render :create_success }
      else
        render "/auctions/show"
      end
    end
  end

  def destroy
    @bid        = Bid.find params[:id]
    @auctions   = Auction.find params[:auction_id]
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to auction_path(@auction), notice: "deleted" }
      format.js { render }
    end
  end


  private

  def bid_params
    params.require(:bid).permit(:amount, :auction_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Awesome"
      redirect_to root_path
    else
      flash[:alert] = "Sorry"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
      redirect_to root_path, notice: 'User was successfully created.'
      else
        render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/index.html.erb
<h2>Welcome </h2>

<% @auction.each do |x| %>
<div>
<%= link_to x.title, x%>
</div>
<% end %>

app/views/auctions/new.html.erb
<div>
<h3>Create an Auction</h3>
<br>
<%= simple_form_for @auction do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price, label: "Reservation Price" %>
  <%= f.input :end_date %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/auctions/show.html.erb
<div>

<div>
<b>Title:</b> <%= @auction.title %>
<br>
<br>
<b>Description:</b><%= @auction.description %>
<br>
<br>
Current Price: <%= @auction.price %>
<br>

AASM STATE: <%= @auction.aasm_state %>
</div>


<div>
<div id="current_bid">
  Current Bid:
</div>
</div>

<div>
  <h2>Bids</h2>
  <%= simple_form_for [@auction, @bid], remote: true do |f|  %>
    <%= f.input :amount %>
    <%= f.submit %>
  <% end %>
</div>

<div>


</div>

<h2>Bids</h2>
<div id="bids">
<% @auction.bids.each do |bid| %>
   <%= render 'bids/bid', bid: bid %>
<% end %>
</div>

app/views/bids/_bid.html.erb
<div id="<%= dom_id(bid) %>">
Bids:
<%= bid.amount %>
User id:<%= bid.auction.user_id %>
<%= link_to "Delete", auction_bid_path(@auction, bid), method: :delete,
              class: "btn btn-sm btn-danger",
              data: {confirm: "Are you sure?"},
              remote: true %>
</div>

app/views/bids/create_success.js.erb
$('#bids').append("<%= j render '/bids/bid', bid: @bid %>").children().first().hide().fadeIn();

<% @bid = Bid.new %>

$('#bid_amount').val("");

app/views/bids/destroy.js.erb
$("#<%= dom_id(@bid) %>").fadeOut();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biddr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="nav nav-tabs">
    <li role="presentation" class="active"><%= link_to "HOME", root_path %></li>
    <li role="presentation"><%= link_to "Sign-UP", new_user_path %></li>
    <li role="presentation"><%= link_to "Sign-IN", new_session_path %></li>
    <li role="presentation"><%= link_to "SIGN OUT", sessions_path, method: :delete %></li>
    <li role="presentation"><%= link_to "Auction", new_auction_path %></li>
  </ul>



 
<div>

<% if user_signed_in? %>
<p>Hi <%= current_user.email  %>
<% end %>
</p>

</div>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div class="container" >

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
   <%= f.label :password %>
   <%= f.password_field :password %>
 </div>
 <div>
   <%= f.label :password_confirmation %>
   <%= f.password_field :password_confirmation %>
 </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">

<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>